### ISSUE TITLE
Issues of GPT2-example

### ISSUE THREAD

**Issue by tdye24** [FederatedAI/FATE-LLM#12]
When I followed the **GPT2-example** in the tutorial, I encountered the following problem. 

<img width="1242" alt="image" src="https://github.com/FederatedAI/FATE-LLM/assets/38368472/10680832-eeef-4b94-b757-d979dde25d76">

By the way, in the **GPT2-example** in the tutorial, the packages of **TrainerParam** and **DatasetParamn** are missing, and they should be imported by 
`from pipeline.component.nn import TrainerParam, DatasetParam `

**Comment by mystery-abby** [comment]
I also faced this problem

**Comment by mgqa34** [comment]
> When I followed the **GPT2-example** in the tutorial, I encountered the following problem.
> 
> <img alt="image" width="1242" src="https://user-images.githubusercontent.com/38368472/245518174-10680832-eeef-4b94-b757-d979dde25d76.png">
> By the way, in the **GPT2-example** in the tutorial, the packages of **TrainerParam** and **DatasetParamn** are missing, and they should be imported by `from pipeline.component.nn import TrainerParam, DatasetParam `

Can you show us the version of fate-client？ Also with the version of fate.

**Comment by tdye24** [comment]
> The version is **1.11.2**. I installed the standalone version following the guidelines 'Install FATE using a Docker image (recommended)' on [page](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy).

**Comment by tdye24** [comment]
> > When I followed the **GPT2-example** in the tutorial, I encountered the following problem.
> > <img alt="image" width="1242" src="https://user-images.githubusercontent.com/38368472/245518174-10680832-eeef-4b94-b757-d979dde25d76.png">
> > By the way, in the **GPT2-example** in the tutorial, the packages of **TrainerParam** and **DatasetParamn** are missing, and they should be imported by `from pipeline.component.nn import TrainerParam, DatasetParam `
> 
> Can you show us the version of fate-client？ Also with the version of fate.

The version is 1.11.2. I installed the standalone version following the guidelines 'Install FATE using a Docker image (recommended)' on [page](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy).

**Comment by mgqa34** [comment]
> > > When I followed the **GPT2-example** in the tutorial, I encountered the following problem.
> > > <img alt="image" width="1242" src="https://user-images.githubusercontent.com/38368472/245518174-10680832-eeef-4b94-b757-d979dde25d76.png">
> > > By the way, in the **GPT2-example** in the tutorial, the packages of **TrainerParam** and **DatasetParamn** are missing, and they should be imported by `from pipeline.component.nn import TrainerParam, DatasetParam `
> > 
> > 
> > Can you show us the version of fate-client？ Also with the version of fate.
> 
> The version is 1.11.2. I installed the standalone version following the guidelines 'Install FATE using a Docker image (recommended)' on [page](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy).

Please refer to [deployment guide](https://github.com/FederatedAI/FATE-LLM#standalone-deployment)， the docker image does not have fate_llm directory.

**Comment by tdye24** [comment]
I have copied directory python/fate_llm to {fate_install}/fate/python/fate_llm, but the error still exists.
