### ISSUE TITLE
How to use model in GPT2-example

### ISSUE THREAD

**Issue by stone-wlg** [FederatedAI/FATE-LLM#17]
Hi,
  I want to know how to use model when i complete GPT2-example, is there any sample or README?
screenshot as below:
<img width="1574" alt="image" src="https://github.com/FederatedAI/FATE-LLM/assets/2622666/4085d931-ff7e-41ae-b068-254d0f3f3298">
i only fetch 3 sample data from IMDB.csv for testing.
<img width="1339" alt="image" src="https://github.com/FederatedAI/FATE-LLM/assets/2622666/a4fc796b-57aa-4a83-9dd5-cce6f5995c63">

**Comment by stone-wlg** [comment]
After several test, i have several conclusions, sharing with you:
 1. use case
reader_0 for train
reader_1 for validate (as predict)
<img width="1537" alt="image" src="https://github.com/FederatedAI/FATE-LLM/assets/2622666/2c42274a-2f57-4165-8798-784a6c97adcf">
<img width="1549" alt="image" src="https://github.com/FederatedAI/FATE-LLM/assets/2622666/4dbeace7-c122-4388-8c2f-6cb8b008208e">
 2. save model
i add save_to_local_dir=True in TrainerParam, but it always save model.pkl, not adapter_config.json and adpater_model.bin, even though i add enable_save_pretrained = True on the top of gpt2.py

**Comment by portalll** [comment]
> 经过多次测试，我有几个结论，与大家分享：
> 
> 1. 使用案例
>    reader_0 训练
>    reader_1进行验证（如预测）
> 
> <img alt="图像" width="1537" src="https://private-user-images.githubusercontent.com/2622666/253906215-2c42274a-2f57-4165-8798-784a6c97adcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQzODIsIm5iZiI6MTcwNTg5NDA4MiwicGF0aCI6Ii8yNjIyNjY2LzI1MzkwNjIxNS0yYzQyMjc0YS0yZjU3LTQxNjUtODc5OC03ODRhNmM5N2FkY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDMyODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRhMDI5MWNlN2IyZDE4YTBmNTdmZjcyZGVhYWUzNjA0MzQ5YzE3NGViMTcyMDlhZDNmMGQwZTlmOWIxZDI3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.87HcR7wHSRmEgXErYGz7V-AQxNO0_StkkebS3rTYqlc"> <img alt="图像" width="1549" src="https://private-user-images.githubusercontent.com/2622666/253906511-4dbeace7-c122-4388-8c2f-6cb8b008208e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQzODIsIm5iZiI6MTcwNTg5NDA4MiwicGF0aCI6Ii8yNjIyNjY2LzI1MzkwNjUxMS00ZGJlYWNlNy1jMTIyLTQzODgtOGMyZi02Y2I4YjAwODIwOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDMyODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdjYTdiZDJjYjExNTFjNzdlZGRhOGUzNDljZGVlMjI3YmNmOTY5NWYyZDAzOGY4MzRjMWRhOGQxODU3NDVmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aXD6KCnkeRyJYJ84FZnRmna5fujuhbAQz4jAmFJSIEg"> 2.保存模型
> 我在TrainerParam中添加save_to_local_dir=True，但它总是保存model.pkl，而不是adapter_config.json和adpater_model.bin，即使我在gpt2.py顶部添加enable_save_pretrained = True

你好，请问能分享下这个任务的DSL和config吗？我尝试通过DSL配置来启动大模型任务
