### ISSUE TITLE
ValueError: IP not configured. Please use command line tool `pipeline init` to set it.

### ISSUE THREAD

**Issue by pxyfxun** [FederatedAI/FATE-LLM#19]
1.错误描述：

![image](https://github.com/FederatedAI/FATE-LLM/assets/29222692/2f55b319-e75d-486c-b835-49a92e93b869)

使用chatglm6b进行联邦大模型训练，报错：
ValueError: IP not configured. Please use command line tool `pipeline init` to set it.

执行pipeline init配置后，仍然报相同错误：
ValueError: IP not configured. Please use command line tool `pipeline init` to set it.

不知道改怎么弄？
哪个大神知道原因吗？

2.背景：

2.1联邦训练代码来源：https://github.com/FederatedAI/FATE-LLM/blob/main/doc/tutorial/ChatGLM-6B_ds.ipynb，只是一些目录改成了本地目录。
2.2部署FATE，使用的是单机版的源码安装，参考连接：https://fate.readthedocs.io/en/latest/zh/deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide/

**Comment by mgqa34** [comment]
需要执行pipeline init --ip $fate_flow_service_ip --port $fate_flow_service_port 后再使用，pipeline构建联邦学习建模工作流，最后会提交任务到flow，所以需要先初始化提供ip/port
