### ISSUE TITLE
在非docker环境的本机standalone_fate环境跑offsite-tuning报错ModuleNotFoundError: No module named 'eggroll

### ISSUE THREAD

**Issue by strongman1995** [FederatedAI/FATE-LLM#37]
报错如下
Traceback (most recent call last):
  File "/home/chenlu/workspace/standalone_fate_install_1.11.3_release/fateflow/python/fate_flow/controller/task_controller.py", line 216, in kill_task
    backend_engine.kill(task)
  File "/home/chenlu/workspace/standalone_fate_install_1.11.3_release/fateflow/python/fate_flow/controller/engine_controller/deepspeed.py", line 134, in kill
    from eggroll.deepspeed.submit import client
ModuleNotFoundError: No module named 'eggroll'

我想问一下standalone环境可以跑fate-llm吗，还是必须需要cluster方式安装才可以？

**Comment by mgqa34** [comment]
standalone下跑的话可以参考gpt2的样例，直接使用单个cuda的训练模式，不能使用deepspeed的集群训练功能，你的报错应该是尝试去提交基于ds的联邦训练任务。

**Comment by strongman1995** [comment]
@mgqa34 我尝试gpt2的样例，在跑local test那部分的时候，有如下报错，我在想是不是peft的版本问题还是其他问题呢？我的gpt2是从huggingface（https://huggingface.co/gpt2/tree/main）下载的[pytorch_model.bin](https://huggingface.co/gpt2/blob/main/pytorch_model.bin)、[config.json](https://huggingface.co/gpt2/blob/main/config.json)、[tokenizer.json](https://huggingface.co/gpt2/blob/main/tokenizer.json)、[vocab.json](https://huggingface.co/gpt2/blob/main/vocab.json)
`TypeError                                 Traceback (most recent call last)
Cell In[15], line 15
     11 ds.load(imdb_path)
     13 checkpoint_path = gpt2_path
     14 model = t.nn.Sequential(
---> 15     GPT2(pretrained_path=checkpoint_path, peft_config=lora_config.to_dict(), peft_type="LoraConfig", num_labels=1,  pad_token_id=50256),
     16     Sigmoid()
     17 )
     19 trainer = FedAVGTrainer(epochs=1, batch_size=8, shuffle=True, data_loader_worker=8)
     20 trainer.local_mode()

File ~/workspace/standalone_fate_install_1.11.3_release/fate/python/fate_llm/model_zoo/pellm/gpt2.py:35, in GPT2.__init__(self, config, pretrained_path, peft_type, peft_config, **kwargs)
     33 if config is None and pretrained_path is None:
     34     config = GPT2Config().to_dict()
---> 35 super().__init__(
     36     config=config,
     37     pretrained_path=pretrained_path,
     38     peft_type=peft_type,
     39     peft_config=peft_config,
     40     **kwargs)

File ~/workspace/standalone_fate_install_1.11.3_release/fate/python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py:54, in PELLM.__init__(self, config, pretrained_path, peft_type, peft_config, **kwargs)
     50 self.peft_config = peft_config
     52 assert self.config_path is not None or self.config is not None, \
     53     "At least one of config_path and config must be set."
---> 54 self._init_pelm(**kwargs)

File ~/workspace/standalone_fate_install_1.11.3_release/fate/python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py:57, in PELLM._init_pelm(self, **kwargs)
     56 def _init_pelm(self, **kwargs):
---> 57     self.init_lm_with_peft(**kwargs)
     58     self.model_summary()

File ~/workspace/standalone_fate_install_1.11.3_release/fate/python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py:63, in PELLM.init_lm_with_peft(self, **kwargs)
     61 self.init_config(**kwargs)
     62 self.init_base_lm()
---> 63 self.add_peft()

File ~/workspace/standalone_fate_install_1.11.3_release/fate/python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py:99, in PELLM.add_peft(self)
     96 else:
     97     peft_config = getattr(peft, self.peft_type)(**self.peft_config)
---> 99 self._pe_lm = peft.get_peft_model(self._pe_lm, peft_config)

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/mapping.py:116, in get_peft_model(model, peft_config, adapter_name)
    114 if peft_config.is_prompt_learning:
    115     peft_config = _prepare_prompt_learning_config(peft_config, model_config)
--> 116 return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/peft_model.py:787, in PeftModelForSequenceClassification.__init__(self, model, peft_config, adapter_name)
    786 def __init__(self, model, peft_config: PeftConfig, adapter_name="default"):
--> 787     super().__init__(model, peft_config, adapter_name)
    788     if self.modules_to_save is None:
    789         self.modules_to_save = {"classifier", "score"}

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/peft_model.py:121, in PeftModel.__init__(self, model, peft_config, adapter_name)
    119     self._peft_config = None
    120     cls = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type]
--> 121     self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
    122     self.set_additional_trainable_modules(peft_config, adapter_name)
    124 self.config = getattr(self.base_model, "config", {"model_type": "custom"})

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/lora/model.py:111, in LoraModel.__init__(self, model, config, adapter_name)
    110 def __init__(self, model, config, adapter_name) -> None:
--> 111     super().__init__(model, config, adapter_name)

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/tuners_utils.py:94, in BaseTuner.__init__(self, model, peft_config, adapter_name)
     91 if not hasattr(self, "config"):
     92     self.config = {"model_type": "custom"}
---> 94 self.inject_adapter(self.model, adapter_name)
     96 # Copy the peft_config in the injected model.
     97 self.model.peft_config = self.peft_config

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/tuners_utils.py:251, in BaseTuner.inject_adapter(self, model, adapter_name)
    244     parent, target, target_name = _get_submodules(model, key)
    246     optional_kwargs = {
    247         "loaded_in_8bit": getattr(model, "is_loaded_in_8bit", False),
    248         "loaded_in_4bit": getattr(model, "is_loaded_in_4bit", False),
    249         "current_key": key,
    250     }
--> 251     self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
    253 if not is_target_modules_in_base_model:
    254     raise ValueError(
    255         f"Target modules {peft_config.target_modules} not found in the base model. "
    256         f"Please check the target modules and try again."
    257     )

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/lora/model.py:193, in LoraModel._create_and_replace(self, lora_config, adapter_name, target, target_name, parent, current_key, **optional_kwargs)
    185     target.update_layer(
    186         adapter_name,
    187         r,
   (...)
    190         lora_config.init_lora_weights,
    191     )
    192 else:
--> 193     new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
    194     if adapter_name != self.active_adapter:
    195         # adding an additional adapter: it is not automatically trainable
    196         new_module.requires_grad_(False)

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/lora/model.py:321, in LoraModel._create_new_module(lora_config, adapter_name, target, **kwargs)
    316     else:
    317         raise ValueError(
    318             f"Target module {target} is not supported. Currently, only the following modules are supported: "
    319             "`torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`."
    320         )
--> 321     new_module = Linear(adapter_name, in_features, out_features, bias=bias, **kwargs)
    323 return new_module

File ~/workspace/standalone_fate_install_1.11.3_release/env/python/venv/lib/python3.8/site-packages/peft/tuners/lora/layer.py:208, in Linear.__init__(self, adapter_name, in_features, out_features, r, lora_alpha, lora_dropout, fan_in_fan_out, is_target_conv_1d_layer, **kwargs)
    205 init_lora_weights = kwargs.pop("init_lora_weights", True)
    206 # this gets the init from nn.Linear's super perspective, i.e.
    207 # nn.Module.__init__, which should always be called
--> 208 super(nn.Linear, self).__init__()
    209 # Note that we don't use self._init_empty_weights() for Linear because it is a bit slower and the benefit of
    210 # added robustness is not big enough for Linear.
    212 LoraLayer.__init__(self, in_features=in_features, out_features=out_features)

TypeError: super(type, obj): obj must be an instance or subtype of type
`

**Comment by strongman1995** [comment]
我发现是因为加载了两次GPT2类就会出现这个问题

**Comment by strongman1995** [comment]
我发现是因为加载了两次GPT2类就会出现这个问题
