### ISSUE TITLE
已经通过docker compose部署了fate_flow，如何在此基础上增加fate_llm?启动大模型任务时能通过DSL启动吗？

### ISSUE THREAD

**Issue by portalll** [FederatedAI/FATE-LLM#42]
目前已经通过docker compose部署了fate_flow，并成功测试了heteroLinR，homoNN等算法。请问在此基础上怎么加载大模型？直接修改配置文件中的算法改为ALL吗？
![1705571528959](https://github.com/FederatedAI/FATE-LLM/assets/43346110/c6764d5c-c410-426f-91e0-e399c38a9b8c)
（目前项目还是用的cpu）。
第二个问题是我只找到了pipeline 实现FATE_LLM样例，请问能通过编写config和DSL来实现LLM吗？

**Comment by dylan-fan** [comment]
2.0后可以用yaml文件写。不过python方式更友好
