### ISSUE TITLE
No module named 'federatedml'

### ISSUE THREAD

**Issue by abhilashadavi** [FederatedAI/FATE-LLM#68]
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

NAME="Debian GNU/Linux"

VERSION_ID="12"

VERSION="12 (bookworm)"

VERSION_CODENAME=bookworm

ID=debian

HOME_URL="https://www.debian.org/"

SUPPORT_URL="https://www.debian.org/support"

BUG_REPORT_URL="https://bugs.debian.org/"

Python version 3.8

Steps followed for installing FATE 1.11.3 version

Pulled a Docker python 3.8 image, mounted the ./FATELLM/python directory to /usr/local/lib/python3.8/site- packages/fate/python in the container and installed the below packages

pip install fate client[fate, fate_flow]==1.11.3

apt update

apt install -y lsof

apt purge python3-click

pip install click==8.1.6

fate_flow init --ip 127.0.0.1 --port 9380 --home/fate_home

pipeline init --ip 127.0.0.1 --port 9380

fate_flow start

After this I appended the fate python path as said in the tutorial.

The below error is after running offset tuning example

"""
import sys

your_path_to_fate_python = '/usr/local/lib/python3.8/site-packages/fate/python'

sys.path.append(your_path_to_fate_python)

from fate_llm.model_zoo.offsite_tuning.offsite_tuning_model import OffsiteTuningSubModel, OffsiteTuningMainModel

"""

Error: 

Traceback (most recent call last): 
File "<stdin>", line 1, in <module>

File "/usr/local/lib/python3.8/site-packages/fate/python/fate_llm/model_zoo/offsite_tuning/offsite_tuning_model.py", line 18, in <module> from federatedml.util import LOGGER

ModuleNotFoundError: No module named 'federatedml'

**Comment by mgqa34** [comment]
pip install fate client[fate, fate_flow]==1.11.3 这个语法是fate-2.0的语法，需要用fate-llm 2.0（当前已经合并到main分支并release)
