### ISSUE TITLE
训练GPT模型卡住

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/FATE-LLM#75]
![image](https://github.com/FederatedAI/FATE-LLM/assets/19503929/46eb4e3d-4876-4c97-9a99-f8cf95ab30a2)
FATE-LLM训练GPT模型时，卡住在这里不动了，最开始以为是资源问题，使用了2台机器上跑，每台1块GPU，结果还是卡住，没报错，也没日志输出。哪位大佬知道怎么调整吗？

**Comment by mgqa34** [comment]
请问是怎么部署的呢？Eggroll的配置正常吗？

**Comment by zapjone** [comment]
部署在2台机器上（每台一块GPU），提交其他任务都可以正常执行成功，按照教程中的这个进行提交的任务就卡住
https://github.com/FederatedAI/FATE-LLM/blob/main/doc/tutorial/parameter_efficient_llm/ChatGLM3-6B_ds.ipynb

**Comment by zapjone** [comment]
> 请问是怎么部署的呢？Eggroll的配置正常吗？

部署在2台机器上（每台一块GPU），提交其他任务都可以正常执行成功，按照教程中的这个进行提交的任务就卡住
https://github.com/FederatedAI/FATE-LLM/blob/main/doc/tutorial/parameter_efficient_llm/ChatGLM3-6B_ds.ipynb

**Comment by mgqa34** [comment]
这里问的是用哪个部署包链接哈，因为其他的几个算法可能没有用到deepspeed

**Comment by zapjone** [comment]
> 这里问的是用哪个部署包链接哈，因为其他的几个算法可能没有用到deepspeed
自己按照FATE-Builder进行打的镜像，代码是使用的最新的2.1的代码（FATE）

**Comment by zapjone** [comment]
![image](https://github.com/FederatedAI/FATE-LLM/assets/19503929/e061a760-5b3c-47ae-acf1-a0610b459f62)

**Comment by robbie228** [comment]
> > 这里问的是用哪个部署包链接哈，因为其他的几个算法可能没有用到deepspeed
> 
> 自己按照FATE-Builder进行打的镜像，代码是使用的最新的2.1的代码（FATE）

使用FATE-Builder打包的时候，如果需要打包fate-llm，需要设置一下变量：
LLM_DIR=  //fate-llm的目录
PACK_LLM=1   //1代表需要打包fate-llm
LLM_VER=2.0.0  //fate-llm的版本号

**Comment by zapjone** [comment]
> > > 这里问的是用哪个部署包链接哈，因为其他的几个算法可能没有用到deepspeed
> > 
> > 
> > 自己按照FATE-Builder进行打的镜像，代码是使用的最新的2.1的代码（FATE）
> 
> 使用FATE-Builder打包的时候，如果需要打包fate-llm，需要设置一下变量： LLM_DIR= //fate-llm的目录 PACK_LLM=1 //1代表需要打包fate-llm LLM_VER=2.0.0 //fate-llm的版本号

设置了的，最后使用的fateflow-all-gpu和eggroll-all-gpu的镜像
