### ISSUE TITLE
FATE-LLM数据上传问题

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/FATE-LLM#76]
https://github.com/FederatedAI/FATE-LLM/blob/main/doc/tutorial/parameter_efficient_llm/ChatGLM3-6B_ds.ipynb
按照这个教程中的指导，需要上传train.json到存储引擎中
{"file":"xxxx/train.json","head",false,"partition":4,"meta":{},"namespace":"experiment","name":"ad"}
上传数据失败。需要需要设置：Please provide sample_id_name

**Comment by mgqa34** [comment]
这里面应该是需要绑定本地数据路径，而不是上传
请注意文档中的： 
To run federated task, please make sure to ues fate>=2.1.0 and deploy it with gpu machines. To running this code, make sure training data path is already binded. The following code shoud be copy to a script and run in a command line like "python federated_chatglm.py"
以及代码中的
# pipeline.bind_local_path(path="", namespace="experiment", name="ad")

**Comment by zapjone** [comment]
> 这里面应该是需要绑定本地数据路径，而不是上传 请注意文档中的： To run federated task, please make sure to ues fate>=2.1.0 and deploy it with gpu machines. To running this code, make sure training data path is already binded. The following code shoud be copy to a script and run in a command line like "python federated_chatglm.py" 以及代码中的 pipeline.bind_local_path(path="", namespace="experiment", name="ad")

2台机器的情况下，9999和10000，在9999使用上面的bind代码运行时，会报在10000上找不到table信息

**Comment by mgqa34** [comment]
每一个(role, party_id)都需要绑定数据
