### ISSUE TITLE
ChatGLM-6B模型训练问题

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/FATE-LLM#77]
各位大佬好，想请假下，在fate中使用LLM训练GPT模型时，报以下错误，根据deepspeed的相关问题和解决，将其fp16禁止掉，但在fate中，将其fp16:{enable:False}后，还是报以下错误，想问下有遇到过这个问题的吗？
环境：
2台3090GPU机器，每台1块GPU。deepspeed==1.13.1
![image](https://github.com/FederatedAI/FATE-LLM/assets/19503929/5f223ad8-bf6e-41d9-a975-0a43c49047aa)

**Comment by mgqa34** [comment]
这个是deepspeed报的错，说明已经训练到最低点，没法再更新权重了，可以调整下学习率这些
