### ISSUE TITLE
FATE-LLM Qwen模型问题

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/FATE-LLM#78]
各位大佬好，想请问下，fate中使用的哪个千问模型？我使用Qwen-7B和Qwen1.5-7B，都无法正常跑起来。使用ChatGLM3-6B是可以正常训练的。

**Comment by zapjone** [comment]
![image](https://github.com/FederatedAI/FATE-LLM/assets/19503929/fe62f268-f5e5-46ce-a0c8-9ac53edbc3ab)
hua换成QWen2模型后，会报这个错误。

**Comment by mgqa34** [comment]
> ![image](https://private-user-images.githubusercontent.com/19503929/333523352-fe62f268-f5e5-46ce-a0c8-9ac53edbc3ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzc4MzUsIm5iZiI6MTcxNjc3NzUzNSwicGF0aCI6Ii8xOTUwMzkyOS8zMzM1MjMzNTItZmU2MmYyNjgtZjVlNS00NmNlLWEwYzgtOWFjNTNlZGJjM2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyMzg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NDZkOGFmNTcyMjNiZTYxZmNlMDRjYjE2YzVkYWJlYmNjMWU0OGNiNTNjNzU4NmE1ZTUyMjcxNjllZjFiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lICyyw1XnvhWq_GNsygnd7ge86xP3JwyA-jLIvidyJI) hua换成QWen2模型后，会报这个错误。

这个报错是需要设置一下lora的target_modules，qwen的不是query_key_value，可以设置为q_proj, v_proj等。
