### ISSUE TITLE
fedkseed_runner  not found in the import path.

### ISSUE THREAD

**Issue by yujingyue9166** [FederatedAI/FATE-LLM#82]
您好，我在运行https://github.com/FederatedAI/FATE-LLM/blob/main/doc/tutorial/fedkseed/fedkseed-example.ipynb 这个示例，Submit Federated Task 这个部分，出现问题
ValueError: Job is failed, please check out job_id=202405310203079396430 in fate_flow log directory
查看日志发现
ValueError: Module: fate.components.components.nn.runner.fedkseed_runner not found in the import path.
请问是什么原因，应该如何处理，谢谢~

**Comment by sagewe** [comment]
@yujingyue9166 目前需要遵从首页教程手动拷贝代码 https://github.com/FederatedAI/FATE-LLM?tab=readme-ov-file#deployment
